using UnityEngine;

/// <summary>
/// PLAYER-06  Animation driver: feeds the actual state of the movement core (CharacterMotorBase) to the Animator.
///
/// Design: reads no input at all -- the animation plays however the body actually moves, with a single data source,
/// which fundamentally avoids "animation and movement out of sync".
///
/// Matching Animator Controller parameters (the set generated by BuildPlayerAnimatorController):
///   Speed   (float)  <- actual horizontal speed normalized 0~1, drives the Idle/Walk/Run blend tree
///   Grounded(bool)   <- whether on the ground
///   Jump    (trigger)<- fired once on the jump event
///
/// The Animator can be on this object or a child (the model); if empty it is searched downward automatically.
///
/// Two pitfalls handled:
///   - Grounded cannot just read motor.IsGrounded -- when the character is switched away / dead the motor is disabled and the value freezes at the last frame;
///     in that case read CharacterController.isGrounded instead (PassiveFall is still calling Move, so it is accurate). Otherwise, when falling to death,
///     the Jump state never sees Grounded and the jump animation loops forever.
///   - On death / respawn, force back to Locomotion and clear the Jump trigger, so the previous life's animation state does not leak into the next.
/// </summary>
public class PlayerAnimator : MonoBehaviour
{
    [Header("References (empty = auto-find)")]
    [SerializeField] private CharacterMotorBase motor;
    [SerializeField] private Animator animator;

    [Header("Tuning")]
    [Tooltip("Smoothing time for the Speed parameter; larger = softer transitions")]
    [SerializeField] private float speedDampTime = 0.1f;

    [Header("State Reset")]
    [Tooltip("State name to force back to on death / respawn (in Base Layer)")]
    [SerializeField] private string locomotionStateName = "Locomotion";

    private static readonly int SpeedId = Animator.StringToHash("Speed");
    private static readonly int GroundedId = Animator.StringToHash("Grounded");
    private static readonly int JumpId = Animator.StringToHash("Jump");

    private CharacterController controller;
    private CharacterDeathHandler death;
    private PlayerConsoleNavigator navigator;   // Optional: provides speed during right-click pathfinding in Operation Mode
    private int locomotionHash;

    private void Reset()
    {
        motor = GetComponent<CharacterMotorBase>();
        animator = GetComponentInChildren<Animator>();
    }

    private void Awake()
    {
        if (motor == null) motor = GetComponent<CharacterMotorBase>();
        if (animator == null) animator = GetComponentInChildren<Animator>();

        if (motor == null) Debug.LogError("PlayerAnimator: CharacterMotorBase not found", this);
        if (animator == null) Debug.LogError("PlayerAnimator: Animator not found", this);

        controller = GetComponent<CharacterController>();
        death = GetComponent<CharacterDeathHandler>();
        navigator = GetComponent<PlayerConsoleNavigator>();
        locomotionHash = Animator.StringToHash(locomotionStateName);
    }

    private void OnEnable()
    {
        if (motor != null) motor.Jumped += OnJumped;
        if (death != null)
        {
            death.onDeath?.AddListener(ResetToLocomotion);
            death.onRespawn?.AddListener(ResetToLocomotion);
        }
    }

    private void OnDisable()
    {
        if (motor != null) motor.Jumped -= OnJumped;
        if (death != null)
        {
            death.onDeath?.RemoveListener(ResetToLocomotion);
            death.onRespawn?.RemoveListener(ResetToLocomotion);
        }
    }

    /// Death / respawn: clear triggers, mark grounded, force back to Locomotion. The previous life's Jump state must not leak into the next
    private void ResetToLocomotion()
    {
        if (animator == null || !animator.isActiveAndEnabled) return;
        animator.ResetTrigger(JumpId);
        animator.SetBool(GroundedId, true);
        animator.SetFloat(SpeedId, 0f);
        if (animator.HasState(0, locomotionHash)) animator.Play(locomotionHash, 0, 0f);
    }

    /// Grounded check: use the motor when enabled (includes groundCheck sphere test); when switched away / dead the motor is disabled, so read the CC instead
    private bool IsGroundedNow()
    {
        if (motor != null && motor.enabled) return motor.IsGrounded;
        return controller != null && controller.isGrounded;
    }

    private void Update()
    {
        if (motor == null || animator == null) return;

        // Actual horizontal speed -> 0~1 (walkSpeed lands mid-range, runSpeed reaches 1)
        // During Operation Mode right-click pathfinding the motor is frozen (PlanarSpeed=0), so read the pathfinding component's actual speed
        float planar = (navigator != null && navigator.IsNavigating)
            ? navigator.PlanarSpeed
            : motor.PlanarSpeed;
        float normalized = motor.MaxSpeed > 0f
            ? Mathf.Clamp01(planar / motor.MaxSpeed)
            : 0f;

        animator.SetFloat(SpeedId, normalized, speedDampTime, Time.deltaTime);
        animator.SetBool(GroundedId, IsGroundedNow());
    }

    // Base class jump event -> play jump (ignored while dead)
    private void OnJumped()
    {
        if (animator == null) return;
        if (death != null && death.IsDying) return;
        animator.SetTrigger(JumpId);
    }
}